//! Byte identity with an independent implementation, over real documents.
//!
//! Every document here is a PINNED conformance vector from
//! `github.com/astrogilda/agent-evidence-vectors`, and every expected canonical
//! form in `canonical/` was produced by that repository's Go implementation, not
//! by this crate. Nothing in this file is invented, and nothing here was
//! generated by the code under test. Provenance, revisions and the exact command
//! are in `tests/vectors/PROVENANCE.md`.
//!
//! What makes this the load-bearing test rather than a second opinion: two
//! implementations in two languages, written from the specification rather than
//! from each other, either agree on the byte for every document or they do not.
//! A semantic test can pass in both while the bytes differ, and the bytes are
//! what gets signed.
//!
//! The Go rail bundles the I-JSON profile and the integers-only tightening into
//! its single entry point, so the comparison runs under
//! `Options::ijson().integers_only(true)`, which is the same profile.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use jcs_admit::{admit_with, Error, Options};

fn dir(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors/cross-rail")
        .join(name)
}

fn read_dir_sorted(name: &str) -> BTreeMap<String, Vec<u8>> {
    let path = dir(name);
    let entries = std::fs::read_dir(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let mut out = BTreeMap::new();
    for entry in entries {
        let entry = entry.unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let file = entry.path();
        if file.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let id = file
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_owned();
        out.insert(
            id,
            std::fs::read(&file).unwrap_or_else(|e| panic!("{}: {e}", file.display())),
        );
    }
    out
}

/// id -> expected error class, read from the committed `refused.tsv`.
fn refusals() -> BTreeMap<String, String> {
    let path = dir("refused.tsv");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|line| {
            let mut fields = line.split('\t');
            let id = fields.next().unwrap_or_default().to_owned();
            let class = fields.next().unwrap_or_default().to_owned();
            (id, class)
        })
        .collect()
}

fn profile() -> Options {
    Options::ijson().integers_only(true)
}

#[test]
fn every_accepted_vector_canonicalizes_to_the_go_rails_bytes() {
    let inputs = read_dir_sorted("input");
    let expected = read_dir_sorted("canonical");
    let refused = refusals();
    assert!(
        !inputs.is_empty(),
        "the corpus is empty, so this test proves nothing"
    );
    // The corpus must account for every input exactly once: an input that is
    // neither in `canonical/` nor in `refused.tsv` would be silently untested,
    // and a corpus that quietly shrinks is how a differential stops differing.
    let mut unaccounted: Vec<&String> = inputs
        .keys()
        .filter(|id| !expected.contains_key(*id) && !refused.contains_key(*id))
        .collect();
    unaccounted.sort();
    assert!(
        unaccounted.is_empty(),
        "inputs with neither an expected form nor a refusal: {unaccounted:?}"
    );

    let mut failures = Vec::new();
    for (id, want) in &expected {
        let Some(input) = inputs.get(id) else {
            failures.push(format!("{id}: an expected canonical form with no input"));
            continue;
        };
        match admit_with(input, &profile()) {
            Ok(got) if got == *want => {}
            Ok(got) => failures.push(format!(
                "{id}: {} bytes, diverges from the Go rail's {} bytes at offset {:?}",
                got.len(),
                want.len(),
                got.iter().zip(want).position(|(a, b)| a != b)
            )),
            Err(e) => failures.push(format!("{id}: refused, and the Go rail did not: {e}")),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} accepted vectors diverge:\n{}",
        failures.len(),
        expected.len(),
        failures.join("\n")
    );
}

#[test]
fn every_refused_vector_is_refused_in_the_same_class() {
    let inputs = read_dir_sorted("input");
    let refused = refusals();
    assert!(
        !refused.is_empty(),
        "no refusal rows, so this test proves nothing"
    );
    let mut failures = Vec::new();
    for (id, want_class) in &refused {
        let Some(input) = inputs.get(id) else {
            failures.push(format!("{id}: a refusal row with no input"));
            continue;
        };
        let got = admit_with(input, &profile());
        let got_class = match &got {
            Err(Error::StringNotScalar { .. }) => "StringNotScalar",
            Err(Error::DuplicateMember { .. }) => "DuplicateMember",
            Err(Error::NonIntegerNumber { .. }) => "NonIntegerNumber",
            Err(Error::UnsafeInteger { .. }) => "UnsafeInteger",
            Err(Error::TooDeep { .. }) => "TooDeep",
            Err(Error::TooLarge { .. }) => "TooLarge",
            Err(Error::NonFiniteNumber { .. }) => "NonFiniteNumber",
            Err(Error::Syntax { .. }) => "Syntax",
            Err(Error::TrailingContent { .. }) => "TrailingContent",
            Err(_) => "other",
            Ok(_) => "ACCEPTED",
        };
        if got_class != want_class.as_str() {
            failures.push(format!(
                "{id}: want {want_class}, got {got_class} ({got:?})"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} refusals diverge:\n{}",
        failures.len(),
        refused.len(),
        failures.join("\n")
    );
}

/// The committed canonical forms are canonical under the DEFAULT profile too, so
/// the two profiles cannot disagree about a document both accept.
#[test]
fn the_go_rails_output_is_canonical_under_the_default_profile() {
    let mut failures = Vec::new();
    for (id, want) in read_dir_sorted("canonical") {
        match jcs_admit::admit(&want) {
            Ok(got) if got == want => {}
            Ok(_) => failures.push(format!("{id}: not a fixed point under the default profile")),
            Err(e) => failures.push(format!("{id}: refused under the default profile: {e}")),
        }
    }
    assert!(
        failures.is_empty(),
        "{} diverge:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
